### ISSUE TITLE
Unattended install ('automated install/basic-install.sh') script in development branch requires interaction.

### ISSUE THREAD

**Issue by drew-kun** [pi-hole/pi-hole#2164]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
non-interactive installation succeeds.

**Actual behaviour:**
The blue screen appears waiting for interactive action.

**Steps to reproduce:**
As per[ this issue](https://github.com/pi-hole/pi-hole/issues/2129) I have ben suggested to test unattended install on **development** branch

```
git clone https://github.com/pi-hole/pi-hole.git /tmp/pi-hole
cd /tmp/pi-hole/
git checkout development
bash /tmp/pi-hole/automated\ install/basic-install.sh
```
![untitled](https://user-images.githubusercontent.com/10493450/39606776-f729c7a2-4eeb-11e8-8241-ab04cf9c9267.png)

How I have noticed it. I was writing ansible playbook for automated pihole setup:
```yml
- name: '[main] Clone pihole repo development branch with --depth 1'
  git:
    repo: https://github.com/pi-hole/pi-hole.git
    depth: 1
    dest: /tmp/pi-hole
    version: development

- name: '[main] Install pihole'
  command: bash '/tmp/pi-hole/automated install/basic-install.sh'
  become: yes
```
Hangs (waiting for interactive input)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`None`

**Troubleshooting undertaken, and/or other relevant information:**

`Issue opened`
