### ISSUE TITLE
Cannot use pihole with Handshake hsd as upstream dns server

### ISSUE THREAD

**Issue by shalzz** [pi-hole/pi-hole#3525]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

dns queries should resolve

**Actual behaviour:**
dns queries do not resolve

**Steps to reproduce:**
This is the docker-compose file I've used for this setup:
```yaml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'supersecretpassword'
      DNS1: 172.15.0.3#53
      DNS2: 172.15.0.3#5300
      DNSSEC: 'True'
      ServerIP: 192.168.1.224
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 172.15.0.3#53
      - 172.15.0.3#5300
    networks:
      dock_net:
        ipv4_address: 172.15.0.2
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
  hsd:
    container_name: hsd
    image: shalzz/hsd:latest
    # Volumes store your data between container upgrades
    volumes:
      - '/media/sda1/hsd-data:/root/.hsd'
    command: 
      - 'hsd'
      - '--ns-port'
      - '5300'
      - '--rs-host'
      - '0.0.0.0'
      - '--rs-port'
      - '53'
      - '--listen'
    networks:
      dock_net:
        ipv4_address: 172.15.0.3
    restart: unless-stopped

networks:
  dock_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.15.0.0/24
```

**Troubleshooting undertaken, and/or other relevant information:**

Manually querying the hsd server works with this output:
```bash
$ dig @172.15.0.3 www.ietf.org +dnssec

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> @172.15.0.3 www.ietf.org +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38457
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
; COOKIE: ae6ff8620d394878 (echoed)
;; QUESTION SECTION:
;www.ietf.org.                  IN      A

;; ANSWER SECTION:
www.ietf.org.           1795    IN      CNAME   www.ietf.org.cdn.cloudflare.net.
www.ietf.org.           1795    IN      RRSIG   CNAME 5 3 1800 20210701190828 20200701181143 40452 ietf.org. nW7NDbKd+E+XCMi+hRWEcZly6bTAJlEDS8RA
RH4xQz+EH46Vn+gJu9nF IdTS3CBKkKc0+ve+DX+QNPR4n8tT6CLKKn2EYbBd0zP9AIWmqz/Nkr1U 56UlnMjznks/2bkUsQmnTy3C6ShTaHdiZO+eEUldoUc/2NDNYA/WvFAI zwei7Ks4f+
aOc6IwqOfL+lVUbhA2IeD4N66iAjMEft9b/9Dqyd25RAl+ n//tn6viZ+/8VPbd0lRy812Y5TkjHxOE1VWTAMZH4+XEDLJCFJr0KCUd pMmRKaIJqaUieqKjOHElywt0IqRm7nCnO6hDsgdGU
uj3RUv7HCyHUw8B qYa+4g==
www.ietf.org.cdn.cloudflare.net. 295 IN A       104.20.0.85
www.ietf.org.cdn.cloudflare.net. 295 IN A       104.20.1.85
www.ietf.org.cdn.cloudflare.net. 295 IN RRSIG   A 13 6 300 20200703131517 20200701111517 34505 cloudflare.net. ervLE6N8sc/0AXFcaCC87a3UchGbxAyeoz
sIxXWovme2U3+X5WO2Cl5N KMMiiY9ZPWqH+uTetXPAGTesyhS52w==

;; SIG0 PSEUDOSECTION:
.                       0       ANY     SIG     0 253 0 0 20200702181523 20200702061523 32465 . 9xjSXpoDW30CLfoApSV6dGjNdce/9KY+ecLXVh7Tnz9IGotwy
LfR2Wmv TsEuKvE4mR+kgaRQdildAjQ4dImnwQ==

;; Query time: 7 msec
;; SERVER: 172.15.0.3#53(172.15.0.3)
;; WHEN: Thu Jul 02 17:45:23 IST 2020
;; MSG SIZE  rcvd: 608
```

But querying pihole server comes up empty. I've get this with both DNSSEC on and off.
```bash
$ dig @172.15.0.2 www.ietf.org +dnssec

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> @172.15.0.2 www.ietf.org +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 43332
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
; COOKIE: 2a2b63d41e3e59c6 (echoed)
;; QUESTION SECTION:
;www.ietf.org.                  IN      A

;; Query time: 14 msec
;; SERVER: 172.15.0.2#53(172.15.0.2)
;; WHEN: Thu Jul 02 17:45:24 IST 2020
;; MSG SIZE  rcvd: 53
```
