### ISSUE TITLE
Teleporter not copying certain things

### ISSUE THREAD

**Issue by modem7** [pi-hole/pi-hole#3635]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behavior:**

Attempting to migrate volumes for PiHole from a Docker Volume to a mount volume. Have attempted a direct copy but certain things are not copied across. 

Have also attempted Teleporter (in this issue, I'll focus on teleporter as it's the Pihole method to back things up).

**Actual behavior:**

Things not copied across: 
DHCP settings + leases
Whitelists
Audit Log
Local DNS Records

**Steps to reproduce:**

Create new PiHole container with the new mount points. Create Teleporter backup on working PiHole instance. Restore on new Pihole instance. 

https://tricorder.pi-hole.net/fguagziwfu

Have checked both #3376 and https://github.com/pi-hole/AdminLTE/pull/1276 as it seems that the issues were fixed, so could be a local/ID10T issue?

Docker config:
```

 ######################
 ##########Pihole Test
 ######################

 #Pihole - Network wide adblocker, DNS cache and DHCP server
  pihole2:
    image: pihole/pihole:latest
    container_name: PiHole2
    hostname: PiHole2
    environment:
      INTERFACE: $INTERFACE
      DNSMASQ_LISTENING: $DNSMASQ_LISTENING
      ServerIP: '192.168.0.5'
      DNS1: $PH_DNS1
      DNS2: $PH_DNS2
      VIRTUAL_HOST: $VIRTUAL_HOST
      TZ: $TZ
    # labels: 
      # - autoheal=true
      # - "traefik.enable=true"
      # ## HTTP Routers Auth Bypass
      # - "traefik.http.routers.pihole-rtr-bypass.entrypoints=https"
      # - "traefik.http.routers.pihole-rtr-bypass.rule=Headers(`X-Api-Key`, `$PIHOLE_API_KEY`) || Query(`apikey`, `$PIHOLE_API_KEY`)"
      # - "traefik.http.routers.pihole-rtr-bypass.priority=100"
      # ## HTTP Routers
      # - "traefik.http.routers.pihole-rtr.entrypoints=https"
      # - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.$DOMAINNAME`)"
      # - "traefik.http.routers.pihole-rtr.priority=99"
      # - "traefik.http.routers.pihole-rtr.tls=true"
      # ## Middlewares
      # - "traefik.http.routers.pihole-rtr-bypass.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.pihole-rtr.middlewares=chain-authelia@file" # Authelia
      # - "traefik.http.middlewares.pihole-add-admin.addPrefix.prefix=/admin"
      # ## HTTP Services
      # - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      # - "traefik.http.routers.pihole-rtr-bypass.service=pihole-svc"
      # - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
     # # Healthcheck
      # - "traefik.http.services.pihole-svc.loadbalancer.healthcheck.interval=5s"
      # - "traefik.http.services.pihole-svc.loadbalancer.healthcheck.timeout=3s"
      # - "traefik.http.services.pihole-svc.loadbalancer.healthcheck.path=/admin"
    cap_add:
      - NET_ADMIN
    networks:
      pihole:
        ipv4_address: '172.22.0.121'
      docker-macvlan:
        ipv4_address: '192.168.0.5'
    dns:
      - 127.0.0.1
      - 9.9.9.9
    # depends_on:
      # - dhcprelay
      # - dnscrypt-proxy
    volumes:
      # - Pihole:/etc/pihole/
      # - Dnsmasq:/etc/dnsmasq.d/
      - $USERDIR/Pihole/pihole:/etc/pihole/
      - $USERDIR/Pihole/dnsmasq.d:/etc/dnsmasq.d/
    restart: always
    mem_limit: 500m
    mem_reservation: 250m
```
