### ISSUE TITLE
Unbound not working when following steps from official guide

### ISSUE THREAD

**Issue by tvmp** [pi-hole/pi-hole#3658]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behavior:**

After following the steps at [https://docs.pi-hole.net/guides/unbound/](https://docs.pi-hole.net/guides/unbound/)  and running the last test validation command

`dig sigok.verteiltesysteme.net @127.0.0.1 -p 5335`

I should be able to see NOERROR plus an IP address according to the official instructions.

**Actual behavior:**

I receive instead
```
; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> sigok.verteiltesysteme.net @127.0.0.1 -p 5335
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 58851
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;sigok.verteiltesysteme.net.    IN      A

;; Query time: 47 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1)
;; WHEN: Wed Aug 05 20:29:45 BST 2020
;; MSG SIZE  rcvd: 55
```

**Steps to reproduce:**

- Install Debian Buster 10.5 minimal or 10.4 (Intel NUC) or Armbian_20.05.7_Odroidxu4_buster_current_5.4.50_minimal (Odroid HC1)
- Install PiHole according to the instructions at [https://docs.pi-hole.net/main/basic-install/](https://docs.pi-hole.net/main/basic-install/)
- Follow the steps at [https://docs.pi-hole.net/guides/unbound/](https://docs.pi-hole.net/guides/unbound/)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

50x7bb5opq

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

Tried several different installations in both a Intel NUC (amd64) and Odroid HC1 with exactly the same result
Reinstalled OS each time and only installed PiHole to test. Same result.
Tried exactly same steps with Rpi 3B+ and 0W and everything works as expected.

**Comment by dschaper** [comment]
What is the exact unbound configuration file contents and what is showing in the unbound logs for the query?

**Comment by dschaper** [comment]
Also note: Configuration and Operation questions are best handled at https://discourse.pi-hole.net/

**Comment by tvmp** [comment]
The configuration is copied from the original instructions at [https://docs.pi-hole.net/guides/unbound/](https://docs.pi-hole.net/guides/unbound/)

```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # Suggested by the unbound man page to reduce fragmentation reassembly problems
    edns-buffer-size: 1472

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
```

Could you please help me on how can I bring up the unbound logs so I can post them here?
