### ISSUE TITLE
Same gravity.db across multiple containers

### ISSUE THREAD

**Issue by Trigus42** [pi-hole/pi-hole#4009]
### Versions
Pi-hole version is v5.2.4 (Latest: v5.2.4)
AdminLTE version is v5.3.1 (Latest: v5.3.1)
FTL version is v5.5.1 (Latest: v5.5.1)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Docker

### Actual behavior / bug
I have two instances of PiHole running in docker. I wanted them to share the same ```gravity.db```. So additionally to the PiHole config directory's which are unique to the containers, I set up a 'volume' in both containers pointing to the same gravity.db file.

It mostly works fine but if you try to update the domains with ```pihole -g``` in one of the containers it errors out:
```
rm: cannot remove '/etc/pihole/gravity.db': Device or resource busy
mv: cannot move '/etc/pihole/gravity_temp.db' to '/etc/pihole/gravity.db': Device or resource busy
```

It might be better to directly modify the ```gravity.db``` file or give the user an option to enable it.

### Steps to reproduce

docker-compose.yml:
```
pihole1:
    image: pihole/pihole:latest
    volumes:
      - '/etc/pihole-docker/gravity.db:/etc/pihole/gravity.db'
      - '/etc/pihole-docker/pihole1/:/etc/pihole/'
      - '/etc/pihole-docker/dnsmasq1/:/etc/dnsmasq.d/

pihole2:
  image: pihole/pihole:latest
  volumes:
      - '/etc/pihole-docker/gravity.db:/etc/pihole/gravity.db'
      - '/etc/pihole-docker/pihole2/:/etc/pihole/'
      - '/etc/pihole-docker/dnsmasq2/:/etc/dnsmasq.d/
```
