### ISSUE TITLE
Docker "-e DNS2: no" doesn't disable the secondary upstream DNS 

### ISSUE THREAD

**Issue by headpoint** [pi-hole/pi-hole#4018]
### Versions
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.1 (Latest: v5.3.1)
  FTL version is v5.5.1 (Latest: v5.5.1)

### Platform
- OS and version:  ArchLinux
- Platform:  Docker

### Expected behavior

Documentation on [hub.docker.com](https://hub.docker.com/r/pihole/pihole) says regarding env variable `DNS2`
```
DNS2: <IP>Optional Default: 8.8.4.4 | Secondary upstream DNS provider, default is google DNS, no if only one DNS should used
```

### Actual behavior / bug

If I set `DNS2: no` I still get it enabled under Settings-DNS (Google 8.8.4.4) and it's **being used as Primary DNS** until I go to Settings-DNS and click "Save" only after that queries are being forwarded to my custom DNS firstly.

### Steps to reproduce

docker-compose.yml
```
  pihole:
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 192.168.1.1
    environment:
      DNS1: 192.168.1.1
      DNS2: "no"
    restart: always
```

### Additional context
Content of /etc/pihole/setupVars.conf
```
IPV6_ADDRESS=0:0:0:0:0:0
PIHOLE_DNS_2=8.8.4.4
LIGHTTPD_ENABLED=true
CACHE_SIZE=10000
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
IPV4_ADDRESS=0.0.0.0
PIHOLE_DNS_1=192.168.1.1
WEBPASSWORD=<removed>
PIHOLE_INTERFACE=eth0
QUERY_LOGGING=true
BLOCKING_ENABLED=true
```
