### ISSUE TITLE
PiHole not answering DNS queries

### ISSUE THREAD

**Issue by Slyke** [pi-hole/pi-hole#4187]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Linux pihole-675d74d56f-b9r5p 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
- Platform: RPi, K3S (Cluster)

### Expected behavior
Should be able to use dig, or nslookup (on Windows) to `10.7.7.245` and have it resolve domain names such as google.com

### Actual behavior / bug
Dig command fails with timeout

### Steps to reproduce

The problem is that I can login to Pihole with the browser, but when doing DNS queries using the same IP, the queries timeout. I have checked that the dnsmasq service is running inside Pihole by exec'ing into the pod and testing dig to localhost. The port configuration is the same for http as it is for DNS (with the exception that the DNS port allows for TCP and UDP traffic). I'm not sure why it's not working. I put all my K3S info on this issue (that I have now closed since I think it's PiHole): https://github.com/k3s-io/k3s/issues/3384

Port 80 works fine on the assigned IP for PiHole and I can login to PiHole and view the dashboard. I changed the "Interface listening behavior" to `Listen on all interfaces, permit all origins`. DNS lookup doesn't seem to work (Tested with Dig on Master). I know Pihole is working correctly since dig command works fine from within the pod:
```
[2021-06-01T03:00:25+0100] [pi@k-m-001] k3s_config $ kubectl exec --stdin --tty pihole-64c4755945-2hlzv -n home -- /bin/bash
root@pihole-64c4755945-2hlzv:/# dig @localhost google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> @localhost google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32906
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             268     IN      A       142.250.217.78

;; Query time: 32 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Jun 01 02:01:09 UTC 2021
;; MSG SIZE  rcvd: 55

root@pihole-64c4755945-2hlzv:/# exit
exit
```

## Debug Token

- URL:  
https://tricorder.pi-hole.net/n97u1i105r

### Additional context
Dig on Windows (WSL2)
```
[2021-05-31T21:46:47-0700] [slyke@WSL2] k3s $ dig @10.7.7.245 google.com

; <<>> DiG 9.16.1-Ubuntu <<>> @10.7.7.245 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

[2021-05-31T21:54:32-0700] [slyke@WSL2] k3s $ while ! nc -w 1 10.7.7.245 53 ; do echo "Attemptign to contact Service"; sleep 1; done; echo "Contacted Service"
Contacted Service
```
nslookup on Windows:
```
C:\Users\Slyke>nslookup google.com 10.7.7.245
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  10.7.7.245

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
```
Dig from Kubernetes Master:
```
[2021-06-01T05:54:10+0100] [pi@k-m-001] k3s_config $ dig @10.7.7.245 google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> @10.7.7.245 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by jfb-pihole** [comment]
```
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the eth0 interface:
   10.42.3.7/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

*** [ DIAGNOSING ]: Setup variables
    ...
    IPV4_ADDRESS=10.7.7.245
    PIHOLE_INTERFACE=eth0

```

**Comment by Slyke** [comment]
@jfb-pihole Thanks for that. I would never have found it! I'm unsure how to fix this. Which IP address does it want? If I give it the pod address (10.42.3.7/24), it could change at any time.

```
root@pihole-675d74d56f-b9r5p:/# cat /etc/pihole/setupVars.conf
BLOCKING_ENABLED=true
WEBPASSWORD=bc463cdd8e177a93efa6131266982b77b4bcf38d55a079e8bc8f741634289f16
ADMIN_EMAIL=
WEBUIBOXEDLAYOUT=boxed
WEBTHEME=default-dark
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
IPV4_ADDRESS=10.7.7.245
PIHOLE_INTERFACE=eth0
QUERY_LOGGING=true
DNSMASQ_LISTENING=all
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=false
REV_SERVER=false
root@pihole-675d74d56f-b9r5p:/# pihole -r

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.27-1~deb10u1
--title Existing Install Detected! --menu \n\nWe have detected an existing install.\n\nPlease choose from the following options: \n(You will remain on the same version) 54 211 2 Repair This will retain existing settings Reconfigure This will reset your Pi-hole and allow you to enter new settings.

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again
  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] SELinux not detected
--msgbox --backtitle Welcome --title Pi-hole automated installer \n\nThis installer will transform your device into a network-wide ad blocker! 54 211
--msgbox --backtitle Plea --title Free and open source \n\nThe Pi-hole is free, but powered by your donations:  https://pi-hole.net/donate/ 54 211
--msgbox --backtitle Initiating network interface --title Static IP Needed \n\nThe Pi-hole is a SERVER so it needs a STATIC IP ADDRESS to function properly.

In the next section, you can choose to use your current network settings (DHCP) or to manually edit them. 54 211
--separate-output --menu Select Upstream DNS Provider. To use your own, select Custom. 54 211 7 Google (ECS)  OpenDNS (ECS, DNSSEC)  Level3  Comodo  DNS.WATCH  Quad9 (filtered, DNSSEC)  Quad9 (unfiltered, no DNSSEC)  Quad9 (filtered + ECS)  Cloudflare  Custom
  [i] Using upstream DNS:  ()
--separate-output --checklist Pi-hole relies on third party lists in order to block ads.\n\nYou can use the suggestion below, and/or add your own after installation\n\nTo deselect the suggested list, use spacebar 54 211 5 StevenBlack StevenBlack's Unified Hosts List on
--separate-output --checklist Select Protocols (press space to toggle selection) 54 211 2 IPv4 Block ads over IPv4 on IPv6 Block ads over IPv6 on
  [i] IPv4 address:
  [i] IPv6 address:
  Error: Neither IPv4 or IPv6 selected
```

Do I need to set the environment variable `ServerIP` to the one I wish to use (`10.7.7.245`)?

**Comment by Slyke** [comment]
Hey @jfb-pihole 

So I figured out a way to have K3s automatically assign the pod's IP to an environment variable:
```
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

And I can clearly see that it's being assigned correctly:
```
root@pihole-5f558c48c6-tz2bn:/# echo $ServerIP
10.42.3.19
root@pihole-5f558c48c6-tz2bn:/# cat /etc/pihole/setupVars.conf
BLOCKING_ENABLED=true
WEBPASSWORD=bc463cdd8e177a93efa6131266982b77b4bcf38d55a079e8bc8f741634289f16
ADMIN_EMAIL=
WEBUIBOXEDLAYOUT=boxed
WEBTHEME=default-dark
DNSMASQ_LISTENING=all
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=false
REV_SERVER=false
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
IPV4_ADDRESS=10.42.3.19
PIHOLE_INTERFACE=eth0
QUERY_LOGGING=true
```

But, I still get that error when running diagnostics: https://tricorder.pi-hole.net/k4mgb6dzi5

And it still doesn't answer DNS queries.

Not sure how to proceed further with this.

**Comment by dschaper** [comment]
Is this a docker based install? The debug logs are not accurate with docker installs.

Please use https://github.com/pi-hole/docker-pi-hole for docker installation issues.

**Comment by Slyke** [comment]
Hey @dschaper , that's the image I'm using:
![image](https://user-images.githubusercontent.com/6442613/120720195-8881d480-c480-11eb-9adc-ad0f4e5e7981.png)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: home
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-webpassword
        image: pihole/pihole
        imagePullPolicy: IfNotPresent
        name: pihole
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-tcp
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-ssl
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole-config
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
status: {}
```

Will try with the `latest` tag set, as shown on the repo you linked.
