### ISSUE TITLE
unable to create  /var/lib/misc/dnsmasq.leases after upgrade to docker 2022.01.1

### ISSUE THREAD

**Issue by klara31** [pi-hole/pi-hole#4523]
### Versions
- Pi-hole:  docker - 2022.01.1
- docker host: debian Linux 11.2 on Raspberry Pi 4

### Actual behavior / bug
When upgrading from version 2021.12.1 to 2022.01.1, Pihole crashes with:
```
pihole  | ::: Testing pihole-FTL DNS: 
pihole  | dnsmasq: cannot open or create lease file /var/lib/misc/dnsmasq.leases: Permission denied
```

### Steps to reproduce
revert to 2021.12.1 and everything works OK. Go to 2022.01.1 and it fails.

### Additional context

My docker-compose:
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.12.1
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=
      - PIHOLE_DNS_=208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
      - DNSSEC=true
      - PIHOLE_DOMAIN=benn.lan
      - ServerIP=192.168.10.245
      - ServerIPv6=fe80::4ed7:3333:4745:4ef7
    volumes:
      - ${USERDIR}/pihole/etc-pihole/:/etc/pihole/
      - ${USERDIR}/pihole/dnsmasq.d/:/etc/dnsmasq.d/
      - /var/lib/misc/dnsmasq.leases:/var/lib/misc/dnsmasq.leases
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    dns:
      - 127.0.0.1
      - 208.67.222.222
      - 208.67.220.220
    restart: always
```
