### ISSUE TITLE
No address range available for DHCP request via eth0

### ISSUE THREAD

**Issue by youngman3009** [pi-hole/pi-hole#4570]
Hello! I have seen this issue countless times online whilst trying to figure out the issue. I am trying to set up Pi-hole as a DHCP server on a Windows 10 machine, using Docker-Compose.

Log uploaded [here](https://tricorder.pi-hole.net/SwMyfw2z/).

I have disabled DHCP on my router and renewed my lease on one of my devices but that just triggers this error in the web interface.

Below is the docker-compose file I'm using.

```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # Already tried deleting ports and replacing with "network_mode: host" but this even stopped the web interface working!
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: 'Some Password'
      INTERFACE: 'eth0' # Read that this is one of the common fixes but no luck!
      FTLCONF_REPLY_ADDR4: '192.168.1.175' # This is the IP address of the machine Im running Pihole on
      DHCP_ACTIVE: 'true' # I know these are set in web interface but I got desperate!
      DHCP_START: '192.168.1.64'
      DHCP_END: '192.168.1.253'
      DHCP_ROUTER: '192.168.1.254'
      DNSMASQ_LISTENING: 'local'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN     
    restart: unless-stopped
```

Any help would be greatly appreciated! Thanks in advance everyone!
