### ISSUE TITLE
5.9.1 - new pihole release stopped working in docker

### ISSUE THREAD

**Issue by tenhishadow** [pi-hole/pi-hole#4672]
### Versions
- Pi-hole:  v5.9.1
- AdminLTE:  v5.11

### Platform
- OS and version:  Debian 11
- Platform:  Docker

### Logs from docker container:
```bash
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Disabling Query Logging
/opt/pihole/piholeLogFlush.sh: line 66: /usr/bin/pihole-FTL: Operation not permitted
  [✓] Flushed /var/log/pihole.log
  [✓] Deleted  queries from database
  [i] Disabling logging...
  [✓] Logging has been disabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Current Pi-hole version is v5.9.1
  Current AdminLTE version is v5.11
/opt/pihole/version.sh: line 23: /usr/bin/pihole-FTL: Operation not permitted
/opt/pihole/version.sh: line 127: /usr/bin/pihole-FTL: Operation not permitted
  Invalid Option! Try 'pihole -v --help' for more information.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
/opt/pihole/updatecheck.sh: line 77: /usr/bin/pihole-FTL: Operation not permitted
/opt/pihole/updatecheck.sh: line 91: /usr/bin/pihole-FTL: Operation not permitted
Setting DNS servers based on PIHOLE_DNS_ variable
::: Pre existing WEBPASSWORD found
DNSMasq binding to default interface: eth0
Added ENV to php:
			"TZ" => "Europe/Warsaw",
			"PIHOLE_DOCKER_TAG" => "2022.04",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.168.1",
			"CORS_HOSTS" => "domain.lan",
			"VIRTUAL_HOST" => "domain.lan",
Using IPv4
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
# adlist customization
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts

::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...

::: Disabling Query Logging
/opt/pihole/piholeLogFlush.sh: line 66: /usr/bin/pihole-FTL: Operation not permitted
  [✓] Flushed /var/log/pihole.log
  [✓] Deleted  queries from database
  [i] Disabling logging...
  [✓] Logging has been disabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Current Pi-hole version is v5.9.1
  Current AdminLTE version is v5.11
/opt/pihole/version.sh: line 23: /usr/bin/pihole-FTL: Operation not permitted
/opt/pihole/version.sh: line 127: /usr/bin/pihole-FTL: Operation not permitted
  Invalid Option! Try 'pihole -v --help' for more information.
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
### Docker run command( ansible )
```yaml
- name: Start/Update pihole container
  docker_container:
    name: "{{ pihole_container_name }}"
    image: "{{ pihole_image }}"
    pull: yes
    restart_policy: always
    env:
      CORS_HOSTS: "{{ pihole_vhost }}"
      DHCP_ACTIVE: "false"
      DNSSEC: "false"
      IPv6: "false"
      PIHOLE_DNS_: "8.8.8.8;8.8.4.4;4.2.2.1;4.2.2.2;1.1.1.1;1.0.0.1"
      QUERY_LOGGING: "false"
      ServerIP: "{{ v_address }}"
      TZ: "{{ timezone }}"
      VIRTUAL_HOST: "{{ pihole_vhost }}"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      PIHOLE_DOMAIN: "{{ pihole_webdomain }}"
    ports:
      - "{{ v_address }}:{{ pihole_port }}:80/tcp"
      - "{{ v_address }}:53:53/udp"
    dns_servers:
      - "127.0.0.1"
    volumes:
      - "{{ ansible_user_dir }}/pihole/pihole_conf:/etc/pihole/"
      - "{{ ansible_user_dir }}/pihole/dnsmasq_conf:/etc/dnsmasq.d/"
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"
```

### Expected behavior

After pulling and running new container tag pihole stopped work
