### ISSUE TITLE
DNS stopped working on user defined non FQDN

### ISSUE THREAD

**Issue by Rod-O** [pi-hole/pi-hole#4758]
### Versions

Docker Tag [2021.12.1](https://github.com/pi-hole/docker-pi-hole/releases/2021.12.1) 
Pi-hole [v5.10](https://github.com/pi-hole/pi-hole/releases/v5.10) 
FTL [v5.15](https://github.com/pi-hole/FTL/releases/v5.15) 
Web Interface [v5.12](https://github.com/pi-hole/AdminLTE/releases/v5.12)

### Platform

- OS and version:  linux

- Platform:  docker

### Expected behavior

DNS Resolving all entries on my list

### Actual behavior / bug

not resolving 

### Steps to reproduce
my case, setup DNS entry:
mqtt -> 10.10.180.35
use nslookup:

### the name is resolved outside, not from the DNS entry
```
rodolfo@computer ~> nslookup mqtt
Server:         10.10.180.35
Address:        10.10.180.35#53

Non-authoritative answer:
Name:   mqtt.localdomain
Address: 23.217.138.108
Name:   mqtt.localdomain
Address: 23.202.231.167
```
### for the DNS to work, I need to add a dot at the end
```
rodolfo@computer ~> nslookup mqtt.
Server:         10.10.180.35
Address:        10.10.180.35#53

Name:   mqtt
Address: 10.10.180.35
```
[✓] Your debug token is:  https://tricorder.pi-hole.net/9Jrhw4es/

**Comment by Rod-O** [comment]
> Please, generate a debug token.
> 
> Then, paste here only the token **URL**, found a few lines before the end of the log:
> 
> ```shell
> [✓] Your debug token is: https://tricorder.pi-hole.net/xxxxxxxx/`.
> ```

https://tricorder.pi-hole.net/9Jrhw4es/

**Comment by dschaper** [comment]
> my case, setup DNS entry:
> mqtt -> 10.10.180.35

How did you create this entry. I don't see anything on the debug log that shows how this was configured.

> Name:   mqtt.localdomain
> Address: 23.217.138.108

That should never happen. `.localdomain` should never resolve to a public IP address. You have `PIHOLE_DNS_1=10.10.180.1` for the config which means that the server at `10.10.180.1` is likely returning that public IP address for the domain queried.

> for the DNS to work, I need to add a dot at the end

If the client you are using is Windows (and it looks like it probably is) then an `nslookup` will always append the configured search domains or configured local domains to a query. Adding the final anchor dot forces `nslookup` to not behave like that. https://community.spiceworks.com/topic/500772-nslookup-to-or-not-to

**Comment by dschaper** [comment]
Do you know if 10.10.180.1 is responding with the public IP address?

Does changing the local DNS entry to `mqtt.localdomain` work?

And lastly, do any of the previous images work now to see if it is indeed a change in the latest image.

A copy of the `docker-compose.yml` or your `docker run` would be very helpful.

**Comment by Rod-O** [comment]
all domains that use *at least one dot* are working, that's how I came up with the idea of using a dot at the end of the word

previous images worked, I don't remember the version of previous image, I just update the image regularly to the latest and restart it

```
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - '82:80'      
    environment:
      TZ: 'US/Eastern'
      WEBPASSWORD: $PIHOLE_WEB_PASSWORD
    volumes:
      - /data/pihole/etc-pihole/:/etc/pihole/
      - /data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
