### ISSUE TITLE
RATE_LIMIT env var is not used

### ISSUE THREAD

**Issue by danielhoherd** [pi-hole/pi-hole#4967]
### Versions

- Pi-hole:  v5.12.2
- AdminLTE:  v5.15.1
- FTL:  v5.18.1

### Platform

- OS and version:  ubuntu 22.04

- Platform:  dell optiplex as docker host running pihole/pihole:2022.09.4

### Expected behavior

Setting `RATE_LIMIT=5000/60` should set the rate limit to 5000 queries per minute, [as described in the docs](https://docs.pi-hole.net/ftldns/configfile/#rate_limit).

### Actual behavior / bug

The rate limit is set to default, 1000/60. This is seen in both the web UI and in `pihole debug`.

### Steps to reproduce

1. Launch [the example docker-compose file](https://github.com/pi-hole/docker-pi-hole#quick-start) with RATE_LIMIT included in the environment section:
```yaml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      RATE_LIMIT: "5000/60"
      WEBPASSWORD: 'hunter2'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```
2. Run `docker-compose up` and notice that `RATE_LIMIT` isn't mentioned anywhere.
3. Check admin/settings.php?tab=dns and observe that the default rate limit is set.
4. In another terminal, run `docker exec -ti pihole /bin/bash -c 'sudo -u pihole cat /proc/$(pgrep -fo /usr/bin/pihole-FTL)/environ'` and observe that the `/usr/bin/pihole-FTL` launcher does have `RATE_LIMIT` in its environment.

## Debug Token

- URL:  https://tricorder.pi-hole.net/nIDNOmAQ/
