### ISSUE TITLE
DNS resolution failure after deploying container

### ISSUE THREAD

**Issue by lazerbeakravage** [pi-hole/pi-hole#5020]
### Versions
- Pi-hole:  5.14.1
- AdminLTE:  5.17
- FTL:  5.19.1

### Platform
- OS and version:  Ubuntu 22.04.1 LTS
- Platform:  Docker Swarm in a VM

### Expected behavior
DNS resolution when deploying a docker container

### Actual behavior / bug
The stack needs to be (re)deployed in a few times then DNS resolution will start to work

host% dig google.com +short +time=1 @pi.hole

; <<>> DiG 9.16.23 <<>> google.com +short +time=1 @pi.hole
;; global options: +cmd
;; connection timed out; no servers could be reached
### Steps to reproduce

```
version: '3.7'
services:
  dash:
    image: pihole/pihole:latest
    networks:
      overlay-network:
    ports:
      - target: 80
        published: 88
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    volumes:
      - /path/to/data/pihole:/etc/pihole
      - /path/to/data/pihole/dnsmasq.d/:/etc/dnsmasq.d
    environment:
      - VIRTUAL_HOST=10.10.10.111
    environment:
      - TZ=America/New_York
      - WEBPASSWORD=########
      - PIHOLE_DNS_=1.1.1.2;9.9.9.9
      - DNS_BOGUS_PRIV=false
      - DNS_FQDN_REQUIRED=false
      - DNSSEC=false
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=example.local
      - REV_SERVER_TARGET=10.10.10.10
      - REV_SERVER_CIDR=10.10.0.0/16
      - WEBTHEME=default-dark
      - DNSMASQ_LISTENING=all
networks:
  overlay-network:
    external: true
```
docker stack deploy -c swarm.yml pihole

## Debug Token
Token generated from it's current state.
- URL:  https://tricorder.pi-hole.net/M0I6fhx7/
