### ISSUE TITLE
example.org will not be resolved

### ISSUE THREAD

**Issue by kirbylink** [pi-hole/pi-hole#5245]
### Versions

- Pi-hole version is v5.16.2
- AdminLTE version is v5.19
- FTL version is v5.22
- Docker Tag [2023.03.1](https://github.com/pi-hole/docker-pi-hole/releases/2023.03.1)

### Platform

- OS and version:  Debian 11.6

- Platform: Raspberry Pi with Docker 

### Expected behavior
I am using Pihole with an unbound service created with docker compose. Pi-Hole uses unbound for resolving DNS.
With the newest docker image the following command will fail:

When executing the command `dig @<IP_of_Raspberry-Pi> +adflag example.org A`
```
; <<>> DiG 9.16.1-Ubuntu <<>> @<IP_of_Raspberry-Pi> +adflag example.org A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58656
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.org.			IN	A

;; ANSWER SECTION:
example.org.		77505	IN	A	93.184.216.34

;; Query time: 8 msec
;; SERVER: <IP_of_Raspberry-Pi>#53(<IP_of_Raspberry-Pi>)
;; WHEN: So Apr 02 19:11:17 CEST 2023
;; MSG SIZE  rcvd: 56
```
should be returned.

### Actual behavior / bug

```
dig @<IP_of_Raspberry-Pi> +adflag example.org A
;; Truncated, retrying in TCP mode.
;; Connection to <IP_of_Raspberry-Pi>#53(<IP_of_Raspberry-Pi>) for example.org failed: connection refused.
```

### Steps to reproduce
I am not sure if this is a docker container problem or if pi-hole itself hast the problem to resolve the domain. If needed, i could add my docker-compose file to the issue.

Docker container that works ootb:

- Pi-hole version is v5.15.5
  AdminLTE version is v5.18.4
  FTL version is v5.21
- Docker Tag [2023.02.2](https://github.com/pi-hole/docker-pi-hole/releases/2023.02.2)

**Comment by rdwebdesign** [comment]
I can't replicate the issue.

Executing `dig 192.168.0.201 +adflag example.org A` the response is: 

```txt
; <<>> DiG 9.11.5-P4-5.1+deb10u8-Raspbian <<>> 192.168.0.201 +adflag example.org A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 61821
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;192.168.0.201.                 IN      A

;; AUTHORITY SECTION:
.                       86397   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2023040200 1800 900 604800 8                                                                     6400

;; Query time: 13 msec
;; SERVER: 192.168.0.201#53(192.168.0.201)
;; WHEN: Sun Apr 02 14:47:14 -03 2023
;; MSG SIZE  rcvd: 117

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25597
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.org.                   IN      A

;; ANSWER SECTION:
example.org.            12865   IN      A       93.184.216.34

;; Query time: 1 msec
;; SERVER: 192.168.0.201#53(192.168.0.201)
;; WHEN: Sun Apr 02 14:47:14 -03 2023
;; MSG SIZE  rcvd: 56
```

Can you please provide a _debug token_ and your compose file or `docker run` command?

**Comment by kirbylink** [comment]
Hi, thanks for the fast response.

Here the Debug Token-URL:  https://tricorder.pi-hole.net/Qt7QCiJ7/

docker-compose file (stripped. Removed labels, comments and a oauth-proxy for web-frontend)

```
version: "3"

services:
  unbound:
    container_name: pihole-unbound
    image: phoenix.ipv64.de/kirbylink/unbound:latest
    restart: unless-stopped
    networks:
      pihole_internal_network:
        ipv4_address: 172.18.1.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/unbound/:/etc/unbound/

  unbound-cron:
    container_name: pihole-unbound-cron
    image: phoenix.ipv64.de/kirbylink/unbound-cron:latest
    restart: unless-stopped
    networks:
      pihole_internal_network:
        ipv4_address: 172.18.1.3
    depends_on:
      - unbound
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/unbound/:/etc/unbound/

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      pihole_internal_network:
        ipv4_address: 172.18.1.4
      traefik_network:
    depends_on:
      - unbound
      - unbound-cron
    environment:
      TZ: Europe/Berlin
      PIHOLE_INTERFACE: eth1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/${APP_NAME}/dnsmasq.d/:/etc/dnsmasq.d/
      - pihole-data:/etc/pihole/
    cap_add:
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE

volumes:
  pihole-data:

networks:
  pihole_internal_network:
    external: true
  traefik_network:
    external: true
```
`unbound` and `unbound-cron` are build locally.
Btw: When i execute `dig @172.18.1.2 +adflag example.org A` in pihole container, i get a successful response.
