### ISSUE TITLE
DataTables warning: table id=domainsTable - Invalid JSON response.

### ISSUE THREAD

**Issue by therealthingy** [pi-hole/pi-hole#5355]
### Versions

  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  Debian bullseye (Raspberry Pi OS Lite 64 bit)

- Platform:  Docker version 24.0.5, build ced0996

### Expected behavior
The page *Domain management* (URL path: admin/groups-domains.php) lists all domains.

### Actual behavior / bug
The page doesn't display the URLs (see screenshot).
This seems to be a serialization issue, as the json appears to be malformed (as shown in the Network tab in the screenshort).

### Screenshots
<img width="1412" alt="Screenshot 2023-07-31 at 11 46 52 AM" src="https://github.com/pi-hole/pi-hole/assets/45701117/b5627834-8ce5-406d-aee5-ab93b2b7bf65">
<img width="1349" alt="Screenshot 2023-07-31 at 11 53 04 AM" src="https://github.com/pi-hole/pi-hole/assets/45701117/8ea515ae-c270-4631-b098-f45a4157ff16">

### Additional context
MAY be related to: https://discourse.pi-hole.net/t/pihole-5-upgrade-error-datatables-warning-table-id-groupstable-ajax-error-for-more-information-about-this-error/32275/24

**Comment by therealthingy** [comment]
eekADXji

**Comment by rdwebdesign** [comment]
There are many web server errors pointing to permission errors:
```log
2023-07-31 11:45:40: chunk.c.624) opening temp-file failed: /var/cache/lighttpd/uploads/lighttpd-upload-SrIxpU: Permission denied
```

Also, there are PHP and FTL errors pointing to a database error ("no such table"):
```log
### PHP error
2023-07-31 11:45:55: mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: message in /var/www/html/admin/api_db.php on line 385

### FTL errors
[2023-07-31 21:05:57.073 1796M] getIfaceFromIP("fe80::42:acff:fe12:4") - SQL error prepare: SQL logic error
[2023-07-31 21:05:57.074 1796M] SQLite3 message: no such table: network in "SELECT aliasclient_id FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ? AND aliasclient_id IS NOT NULL GROUP BY ip HAVING max(lastSeen));" (1)
[2023-07-31 21:05:57.074 1796M] getAliasclientIDfromIP("fe80::42:acff:fe12:4") - SQL error prepare: SQL logic error
[2023-07-31 21:06:00.080 1796/T1816] SQLite3 message: no such table: network_addresses in "DELETE FROM network_addresses WHERE lastSeen < 1659294360;" (1)
[2023-07-31 21:06:00.080 1796/T1816] ERROR: SQL query "DELETE FROM network_addresses WHERE lastSeen < 1659294360;" failed: SQL logic error (SQLITE_ERROR)
```

Is this a fresh install or did you update from a previous container?
If you updated, is the container using volumes?

**Comment by therealthingy** [comment]
I've always upgraded from prior pihole docker images.

This is my docker-compose file:
```
version: "3.7"

networks:
  reverse_proxy:
    external: true

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole
    restart: always

    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp

    environment:
      TZ: Europe/Berlin

      PIHOLE_UID: 1000
      WEB_UID: 1000
      PIHOLE_GID: 1000
      WEB_GID: 1000

      PIHOLE_DNS_: 1.1.1.1;2606:4700:4700::1111
      WEBPASSWORD: xxxxxxxxxxx

      IPv6: "true"

      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.rpi.lan
      VIRTUAL_PORT: 80

    # Volumes store your data between container upgrades
    volumes:
       - /home/xxx/pihole/data/hole/:/etc/pihole/
       - /home/xxx/pihole/data/dns/:/etc/dnsmasq.d/

    networks:
      - reverse_proxy

    dns:
      - 1.1.1.1
      - 2606:4700:4700::1111

    cap_add:
      - NET_ADMIN


    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.monitor-only=true
      - traefik.enable=true
      - traefik.http.services.pihole_service.loadbalancer.server.port=80
      - traefik.http.routers.pihole_router.rule=Host(`pihole.rpi.lan`)
```
As can be seen, I'm currently using bind mounts.

I've also deleted the old `data` folder and restored the settings via Teleporter.
The issue still persists however.

I assume `PIHOLE_UID` & GID is probably wrong?
( I always try to run containers as non-root )
