### ISSUE TITLE
In an LXC container, the website displays a ‘load average’ that is very different from top

### ISSUE THREAD

**Issue by juancarlosromerogarcia** [pi-hole/pi-hole#5565]
### Versions
Pi-hole version is v5.17.3 (Latest: v5.17.3)
web version is v5.21 (Latest: v5.21)
FTL version is v5.24 (Latest: v5.24)

### Platform
The platform is an LXC container that uses a Debian 12 template on a Proxmox VE 7.4.

### Expected behavior
I expected to see the same load average values on the web as shown by the `top `command (around 1).

### Actual behavior / bug
However, instead, values around 5 (belonging to the host) are displayed.

### Steps to reproduce

- Create an LXC container in Proxmox with the following file configuration `104.conf`:

```
arch: amd64
cores: 2
hostname: pihole
memory: 1024
net0: name=eth0,bridge=vmbr1,firewall=1,gw=192.168.10.10,hwaddr=5A:2F:72:71:00:76,ip=192.168.10.40/24,type=veth
ostype: debian
rootfs: backup:104/vm-104-disk-0.raw,size=8G
swap: 1024
unprivileged: 1
```

`apt update && apt upgrade`
`cd ~`
`wget -O basic-install.sh https://install.pi-hole.net`
`bash basic-install.sh`
`apt install unbound -y`
`nano /etc/unbound/unbound.conf.d/pi-hole.conf`

```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines.
    # In reality for most users running on small networks or on a single machine, it should
    # be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
```
`nano /etc/dnsmasq.d/99-edns.conf`

```
edns-packet-max=1232
```
Through the web, uncheck all Upstream DNS Servers and check and add a custom `127.0.0.1#5335`.

## Debug Token
- URL: https://tricorder.pi-hole.net/88nrka0D/ 

### Screenshots

![top](https://github.com/pi-hole/pi-hole/assets/43793527/16b656cd-632d-482b-bce0-5402cce42271)

![web](https://github.com/pi-hole/pi-hole/assets/43793527/7ec5aaea-3d00-4cec-ab5a-ac06dbaaf26c)
