### ISSUE TITLE
Pihole stop working at all after reboot. Can't access internet by itself

### ISSUE THREAD

**Issue by GAS85** [pi-hole/pi-hole#5594]
### Versions

- Pi-hole:  5.9
- AdminLTE:  -1
- FTL:  5.14

### Platform

- OS and version:  Ubuntu 22.04

- Platform:  Baremetal

### Expected behavior

After reboot Pihole can work as expected.

### Actual behavior / bug

After reboot Pihole can't update Gravity -- all connections were refused. It didn't answer to any requests, all of them were refused.
All `dig` commands finished with an error. If I use external DNS server, e.g. `dig @8.8.8.8 google.com` it was ok.
Here is debug log: https://sitnikov.eu/pastebin/J21uAtL_nIILL_Xl0boxs

Only what helped is to update `netplan` and add there google DNS:
```
network:
  version: 2
  ethernets:
    enp5s0:
      addresses:
      - "192.168.0.9/24"
      nameservers:
        addresses:
        - 192.168.0.9 # This is Pihole Server
        - 8.8.8.8     # This what I add to solve the issue.
        search:
        - fritz.box
      gateway4: 192.168.0.1
```

And Pihole Diagnosis is full of following error:
```
2024-03-01 23:12:06	DNSMASQ_WARN	Warning in dnsmasq core:

ignoring nameserver 192.168.0.9 - local interface

Check out [our documentation](https://docs.pi-hole.net/ftldns/dnsmasq_warn/) for further information.
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/sOiMA8ls/

### Screenshots

![изображение](https://github.com/pi-hole/pi-hole/assets/6813635/c3b0f97f-d570-47dd-9fb2-92526278e30c)
