### ISSUE TITLE
Excessive usage of queries to `github.com`, Pi-hole v6, Docker, `development` tag

### ISSUE THREAD

**Issue by akordowski** [pi-hole/pi-hole#5811]
### Versions

![Image](https://github.com/user-attachments/assets/41822286-5dba-481e-a3e8-4521a54e1fa2)

### Platform

- OS and version:
Raspbian

- Platform:
Raspberry Pi, Docker

### Actual behavior / bug

After a long time I checked today the Pi-hole dashboard and have seen an excessive usage of queries to `github.com`, in the last 24h it was over 94k. I run the `development` version of Pi-hole v6 in a Docker container on a Raspberry Pi.

My investigation have shown that the queries are triggered by the Pi-hole Docker container network. As the screenshot below shows this queries are triggered every 3 seconds or so.

What causes this behaviour? Is there a way to fix it? Any help is much appreciated. Thank you in advance.

![Image](https://github.com/user-attachments/assets/ee76fda9-94f2-4c92-89fd-74752a9c9a20)

![Image](https://github.com/user-attachments/assets/0c7c2541-22e7-4efa-8e29-fdf47c06a3f6)

**Comment by rdwebdesign** [comment]
This is not normal. 

> What causes this behaviour?

Usually Pi-hole container only connect to Github to check for updates, but only once a day.
Maybe a device using Pi-hole as DNS server is constantly trying to access github.com. 

We need more information.
Please generate a debug log, upload it and post here **only the Token**.

**Comment by akordowski** [comment]
Thank you for your response. I attached the files.

Here also some screenshots how the dashboard looks like after 24h of running. I hope you can find something. I'm bit concerned as I have not observed such behavior in previous versions.

![Image](https://github.com/user-attachments/assets/e808372f-d21c-4012-908d-1254e0cc314a)
![Image](https://github.com/user-attachments/assets/e1277d8e-534c-46fb-bcdc-0837e10ff8f9)
![Image](https://github.com/user-attachments/assets/199258f8-0201-431c-8922-1be4f52d99b6)

[pihole_debug.log](https://github.com/user-attachments/files/17598236/pihole_debug.log)

docker-compose.yml
```yml
version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:development
    hostname: pi.hole
    environment:
      - TZ=${TZ}
      - FTLCONF_webserver_api_password=${PASSWORD}
      - FTLCONF_dns_upstreams=${DNS_UPSTREAMS}
      - DNSMASQ_LISTENING=all
    ports:
      - "53:53/tcp"
      - "192.168.178.2:53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./etc/dnsmasq.d:/etc/dnsmasq.d
      - ./etc/pihole:/etc/pihole
    restart: unless-stopped
```
