### ISSUE TITLE
SQL - no more rows available

### ISSUE THREAD

**Issue by enzofoucaud** [pi-hole/pi-hole#5815]
### Versions
Docker Tag development
Core vDev (development, 112b9617)
FTL vDev (development, 848367fa)
Web interface vDev (development, c689fdc7)

### Platform
- OS and version: Ubuntu 22.04
- Platform: Docker

### Actual behavior / bug

ERROR: gravity_updated(): SELECT value FROM info WHERE property = 'updated'; - SQL error step: no more rows available

### Steps to reproduce

```yaml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:development
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8081:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "8082:443/tcp"
    environment:
      TZ: 'Europe/Paris'
      FTLCONF_webserver_api_password: 'YWm30Gyt'
    volumes:
      - pihole-etc:/etc/pihole
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  pihole-etc:
```

### Screenshots

![Image](https://github.com/user-attachments/assets/e1597eba-7aaa-4c16-9de0-a28f0d59d72f)
