### ISSUE TITLE
V6 dnsmasq dhcp-option being ignored

### ISSUE THREAD

**Issue by shyamdhokia1** [pi-hole/pi-hole#5911]
### Versions

Core version is v6.0 (Latest: v6.0)
Web version is v6.0 (Latest: v6.0)
FTL version is v6.0 (Latest: v6.0)

### Platform

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

- Platform:  Docker

### Expected behavior

I had bridge networking working with Docker using this [guide](https://discourse.pi-hole.net/t/dhcp-with-docker-compose-and-bridge-networking/17038/1) from the wiki. I have SWAG (NGINX) running to reverse proxy all my other containers so this was needed. The only difference is I use this [image](https://github.com/homeall/dhcphelper) instead of the Dockerfile provided

The end of the guide notes an issue where local devices will see the DNS ip as 172.27.0.100 (or whatever the internal docker network ip is for pihole) and be unable to reach it. It recommends creating a configuration file `07-dhcp-options` to the dnsmasq.d folder with this config.

`dhcp-option=option:dns-server,x.x.x.x`

This was correctly enabling local devices to see the DNS server as 192.168.0.67 (docker host IP) before the update

### Actual behavior / bug

The config appears to be ignored and DNS server shows as 172.27.0.100 for local devices.

### Steps to reproduce

Here is my docker-compose:

```yaml
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '...'
      DNSMASQ_LISTENING: all
    volumes:
      - '/home/red/pihole/pihole:/etc/pihole'
      - '/home/red/pihole/dnsmasq.d:/etc/dnsmasq.d'
    depends_on:
      - dhcphelper
    networks:
      lsio:
        ipv4_address: '172.27.0.100'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  dhcphelper:
    container_name: dhcphelper
    image: homeall/dhcphelper:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      IP: '172.27.0.100'
      TZ: 'Europe/London'
    cap_add:
      - NET_ADMIN

networks:
  lsio:
    external: true

```

## Debug Token

- URL:  https://tricorder.pi-hole.net/jsLtuSnX/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I will be removing pihole from watchtower for next time...whoops. The update also corrupted the sqlite db which I have now fixed.
