### ISSUE TITLE
After uptating Pi-Hole to v6 on Synoloy NAS it does not work anymore - getrandom() failed in generate_password()

### ISSUE THREAD

**Issue by G-3-3-R-T** [pi-hole/pi-hole#5958]
### Versions

DiskStation:/# pihole -v
Core version is v6.0.3 (Latest: v6.0.3)
Web version is v6.0.1 (Latest: v6.0.1)
FTL version is v6.0.2 (Latest: v6.0.2)

### Platform
- OS and version: Linux version 3.10.108 (root@build7) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Mar 24 00:28:41 CST 2023

- Platform:  Synology NAS DS1517+ / INTEL Atom C2538 x86

### Actual behavior / bug

Since updating to v6 it stops and exit, in the log there are two errors.

 ```
2025-02-21 20:08:00.655 UTC [58M] ERROR: getrandom() failed in generate_password()
 2025-02-21 20:08:00.655 UTC [58M] ERROR: Failed to generate CLI password hash
```

### Steps to reproduce

This is the Portainer compose I use:

```
services:
  pihole:
    image: pihole/pihole
    container_name: pi-hole
    network_mode: host
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
    environment:
      TZ: Europe/Brussels
      FTLCONF_webserver_api_password: pihole
      FTLCONF_webserver_port: 8181
      FTLCONF_debug_api: 'true'
      DNSMASQ_USER: root # root is required for Synology NAS'ses
      PIHOLE_UID: 1027
      PIHOLE_GID: 101
    cap_add:
      - SYS_TIME
      - SYS_NICE
```

## WORKAROUND

When leaving the password empty at `FTLCONF_webserver_api_password:` Pi-Hole will work.
