### ISSUE TITLE
dhcp-option with dns-server is not used

### ISSUE THREAD

**Issue by vanupied** [pi-hole/pi-hole#6003]
### Versions
Core version is v6.0.4 (Latest: v6.0.4)
Web version is v6.0.1 (Latest: v6.0.1)
FTL version is v6.0.2 (Latest: v6.0.2)

### Platform

- OS and version:  Raspbian

- Platform:  Docker

### Expected behavior

pihole is behind traefik reverse proxy which handle the WebUI access. Pihole act as DHCP server and because its network it not configured as host it need a docker dhcp-helper to forward DHCP request from LAN client to pihole server.
because of an issue we have to add a file in /etc/dnsmasq.d/07-dhcp-options containing this line
`dhcp-option=option:dns-server,192.168.1.50`
where 192.168.1.50 is the DNS ip address of docker host which host pihole container (and dhcp-helper).
This config was deployed since a year and working correctly. containers are automaticaly updated through watchtower.

### Actual behavior / bug
Since recently pihole update pushed by watchtower it appear that pihole doesn't take in account the  /etc/dnsmasq.d/07-dhcp-options file and client of my network keep recieving ip from pihole container as DNS server

### Steps to reproduce

here is the docker-compose file I used to deploy (it has been modified since without beeing updated and need manual action such as connection to the pihole container and creating the /etc/dnsmasq.d/07-dhcp-options).
This mean this docker-compose should not work as-is.
the dhcp-helper container is built using this dockerfile:

```
FROM debian:stable
RUN apt-get update && apt-get dist-upgrade -y && apt-get install dhcp-helper -y && apt-get clean
EXPOSE 67 67/udp
ENTRYPOINT ["dhcp-helper", "-n"]
```

And here is the docker-compose.yml file

```
version: "3.5"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      - "8080:8080"
      #- "69:69/udp"
    command:
      # api configuration
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=false"
      # - "--log.filepath=traefik.log"
      # - "--log.level=WARN"
      # global config
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      # entrypoints declaration
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web_secure.address=:443"
      # DNS entrypoint
      - "--entrypoints.dnstcp.address=:53"
      - "--entrypoints.dnsudp.address=:53/udp"
      # TFTP entrypoint
      #- "--entrypoints.tftp.address=:69/udp"
      # metrics entrypoint
      - "--entrypoints.metrics.address=:8090"
      # declare docker provider
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      #- "--providers.docker.swarmmode=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/data/rules"
      # lets encrypt declaration
      - "--certificatesresolvers.letsencrypt=true"
      - "--certificatesresolvers.letsencrypt.acme.email=letsencrypt@letsencrypt.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/certificates/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      #metrics backend declaration
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
    networks:
      proxy: {}
      backend:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - traefik-data:/data

pihole:
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # to fix DHCP dns reply with the IP of the container:
    # echo "dhcp-option=option:dns-server,192.168.2.1" > /etc/dnsmasq.d/07-dhcp-options
    container_name: pihole
    image: pihole/pihole:latest
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
      # - "67:67/udp"
      # - "80:80/tcp"
    # dns:
    #   - 127.0.0.1
    #   - 8.8.8.8
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'password'
      PIHOLE_DNS_: 8.8.8.8;8.8.8.4
      DNSMASQ_USER: root
      FTLCONF_LOCAL_IPV4: 192.168.1.251
      VIRTUAL_SERVER: 192.168.1.250
      WEB_PORT: 80
      DHCP_ACTIVE: "true"
      DHCP_START: 192.168.1.50
      DHCP_END: 192.168.1.100
      DHCP_ROUTER: 192.168.1.1
      # INTERFACE: br0
      DNSMASQ_LISTENING: all
    # Volumes store your data between container upgrades
    volumes:
      - 'etc-pihole/:/etc/pihole/'
      - 'etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - CAP_SYS_NICE
      - CAP_SYS_TIME
    restart: unless-stopped
    depends_on:
      - dhcphelper
    networks:
      backend:
        ipv4_address: '172.31.0.100'
      # proxy: {}
    labels:
      #web interface
      - "traefik.enable=true"
      - "traefik.docker.network=backend-network"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(pihole.tools-fm.com)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # DNS TCP
      - "traefik.tcp.routers.dnstcp.entrypoints=dnstcp"
      - "traefik.tcp.routers.dnstcp.rule=HostSNI(*)"
      - "traefik.tcp.routers.dnstcp.service=pihole"
      # DNS UDP
      - "traefik.udp.routers.dnsudp.entrypoints=dnsudp"
      - "traefik.udp.routers.dnsudp.service=pihole"
      - "traefik.udp.services.pihole.loadbalancer.server.port=53"
      # - "traefik.udp.services.pihole.loadbalancer.passHostHeader=true"
      # Service to recieve both TLS and non TLS
      - "traefik.tcp.services.pihole.loadbalancer.server.port=53"
      # - "traefik.http.routers.pihole.service=nginx-http"
      # - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # - "traefik.http.services.nginx-http.loadbalancer.servers.url="



  dhcphelper:
    build: ./pihole/dhcp-helper
    container_name: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

networks:
  backend:
    name: backend-network
    ipam:
      config:
        - subnet: 172.31.0.0/16
  proxy:
    external: true

volumes:
 etc-pihole:
  driver: local
  name: pihole-etc-pihole
 etc-dnsmasq.d:
  driver: local
  name: pihole-etc-dnsmasq.d
 traefik-data:
  driver: local
  name: traefik-certificates

```

## Debug Token

- URL:  [https://tricorder.pi-hole.net/bLACecfg/](https://tricorder.pi-hole.net/bLACecfg/)

### Screenshots

![Image](https://github.com/user-attachments/assets/fff9ea40-9da4-40f6-99e5-8547e2771c70)
