### ISSUE TITLE
Pi-hole v6 Docker: /etc/dnsmasq.d/01-pihole.conf Not Generated, Settings Not Applied (Debian 12 / Kernel 6.12 / Docker 28)

### ISSUE THREAD

**Issue by artinflight** [pi-hole/pi-hole#6178]
Environment:

Pi-hole Version:
Docker Tag: latest (2025.04.0), also tested 2025.03.0
Pi-hole Core: v6.0.6
Pi-hole Web: v6.1
Pi-hole FTL: v6.1
Host OS: Debian GNU/Linux 12 (bookworm) (Raspberry Pi OS based)
Host Architecture: aarch64
Kernel: Linux homelab1 6.12.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.20-1+rpt1~bpo12+1 (2025-03-19) aarch64 GNU/Linux
Docker Version: Docker version 28.0.4, build b8034c0
Installation Method: Docker Compose
Filesystem: ext4
Problem Description:

After setting up Pi-hole v6 using Docker Compose (details below), the primary generated dnsmasq configuration file, /etc/dnsmasq.d/01-pihole.conf, is never created. This occurs even during the very first startup with fresh, empty volume directories.

Consequently, settings configured via the Web UI (e.g., Upstream DNS Servers, Interface Listening Mode changes requiring config file updates) are not applied or persisted, although the UI might report success upon saving. Basic DNS resolution might work using defaults compiled into FTL or read from pihole.toml, but configuration via the UI is broken.

The issue persists across multiple Pi-hole Docker image tags (latest/2025.04.0 and 2025.03.0).

Steps to Reproduce:

Use the following docker-compose.yml file (saved as ~/docker/network/docker-compose.yml):
YAML

```
version: '3.8'

services:
  pihole:
    image: ghcr.io/pi-hole/pihole:latest # Also tested with :2025.03.0
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80" # Web admin on 81
    environment:
      TZ: "America/Toronto"
      FTLCONF_webserver_api_password: "********" # Actual password used
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - app_network

  # Minimal nginx definition included for context, issue persists without it
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx/config:/etc/nginx'
      - './nginx/log:/var/log/nginx'
      - './nginx/html:/usr/share/nginx/html'
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - pihole

networks:
  app_network:
    driver: bridge
```
Ensure host directories ~/docker/network/pihole/etc-pihole and ~/docker/network/pihole/etc-dnsmasq.d are empty or removed.
Ensure parent directory ~/docker/network/pihole is owned by the user running Docker (UID/GID 1000 in this case).
Run docker-compose up -d pihole from ~/docker/network/.
Wait 1-2 minutes for initialization.
Check the contents of the dnsmasq directory inside the container: docker exec pihole ls -l /etc/dnsmasq.d/.
Observe the directory is empty.
Access the Web UI, attempt to change and save settings (e.g., Upstream DNS). The UI reports success.
Re-check docker exec pihole ls -l /etc/dnsmasq.d/ -> still empty. Settings change had no effect.

Troubleshooting Steps Taken:

Verified host directory permissions (drwxr-xr-x, owned by UID 1000).
Verified container pihole-FTL process runs as UID 1000.
Verified pihole user inside container maps to UID 1000.
Performed "Clean Slate" install by removing and recreating empty host volume directories.
Verified database integrity using pihole -d -c on a previously failed attempt (showed intact DBs).
Corrected compose file environment variable from WEBPASSWORD to FTLCONF_webserver_api_password.
Attempted manual regeneration via docker exec pihole pihole -g and docker exec pihole pihole reloaddns (no errors, but no file created).
Tested changing etc_dnsmasq_d to true in pihole.toml on a non-fresh install (did not help).
Watched container startup logs directly (docker-compose up pihole) - no relevant errors observed during initialization or FTL startup.
Tested Pi-hole Docker image tags latest (2025.04.0) and 2025.03.0.

Expected Behavior:

/etc/dnsmasq.d/01-pihole.conf should be generated automatically by Pi-hole during initial startup based on default settings.
Saving settings via the Web UI should successfully update the configuration, likely involving regeneration or modification of 01-pihole.conf or related files/database entries.

Actual Behavior:

/etc/dnsmasq.d/01-pihole.conf is never created.
Relevant settings changes via the Web UI fail silently without error, leaving the configuration unchanged.

Additional Information:

Host Filesystem: /dev/root ext4 122322964 6784056 109305588 6% / (running df -T . from ~/docker/network/)
