### ISSUE TITLE
Container start and Gravity Update fighting regarding group permissions of /etc/pihole

### ISSUE THREAD

**Issue by JBarrskog** [pi-hole/pi-hole#6189]
This is a: Run Issue

## Details

There seems to be a conflict between which permissions /etc/pihole should have. `pihole -g` conflicts with the permissions set by creating the container with `docker compose up -d`

When starting the container, `/etc/pihole` is changed to 0755. However, when running the gravity update, the directory is changed to `76X`(where X is whatever it was before).

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Debian (on Proxmox) 
  * Hardware: PC 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: N/A 
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```
---
services:
  pihole:
    container_name: pihole
    hostname: pihole
    environment:
      TZ: <TZ>
      <FTLCONF_*>
      PIHOLE_DOMAIN: <DOMAIN>
      PIHOLE_UID: "995"
      PIHOLE_GID: "993"
    image: "pihole/pihole:2025.03.1"
    logging:
      driver: "json-file"
      options: {}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    restart: "unless-stopped"
    volumes:
      - "./pihole/dnsmasq:/etc/dnsmasq.d"
      - "./pihole/etc:/etc/pihole"
```

3. any additional info to help reproduce
Before starting container
```
$ chmod 754 etc

$ ls -alt
drwxr-xr-- 7 pihole pihole 4096 Apr  6 14:32 etc
     ^ This bit!

$ docker compose up -d

$ ls -alt
drwxr-xr-x 7 pihole pihole 4096 Apr  6 14:34 etc
     ^ This bit!

$ docker exec -it pihole pihole -g

$ ls -alt
drwxrwxr-x 7 pihole pihole 4096 Apr  6 14:35 etc
     ^ This bit!

$ docker restart pihole

$ ls -alt
drwxr-xr-x 7 pihole pihole 4096 Apr  6 14:36 etc
     ^ This bit!
```

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [-] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [-] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
