### ISSUE TITLE
Missing 'Local DNS' Option from Side Main Menu! No longer able to edit Local Hosts!

### ISSUE THREAD

**Issue by SemoTech** [pi-hole/pi-hole#6201]
### Versions

- Pi-hole:  v6.0.6
- Web:  v6.1
- FTL:  v6.1

### Platform

- OS and version:  Ubuntu 24.04

- Platform:  Docker

### Expected behavior

_I was always able to edit Local DNS Entries on Pi-hole and the 'Local DNS' option has always been there. However I just noticed that the menu option is now gone for me!_

### Actual behavior / bug

_Once logged-in as Admin the Main Web Interface Sidebar no longer shows the "Local DNS" option!  
I also saw an NTP error but unsure why that is happening now and does not seem related._

### Steps to reproduce

See screenshot of expected menu options and screenshot of current options:

What is Expected (shows a 'Local DNS' Menu option):
![Image](https://github.com/user-attachments/assets/1370a857-46f4-4da3-98ea-fab9f37f03af)

What I got (Missing the 'Local DNS' Menu option):
![Image](https://github.com/user-attachments/assets/d516fddb-a10d-40c8-bf58-b5fd38dffa53)

## Sanitized Pi-hole Debug Logs

- URL:  https://pastebin.com/5Um7UJ6r

### Screenshots

_see above_

### Additional context

_Pi-hole is setup in Docker to be automatically updated using Watchtower. Here is it's docker-compose file:_

```
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"      
      - "67:67/udp"
      - "8053:80/tcp"
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - TZ=America/New_York      

      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - pihole/:/etc/pihole/
      - pihole/ssl:/etc/lighttpd/conf-enabled
      - pihole/dnsmasq.d/:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      pihole-net: 


networks:
  pihole-net:
    name: pihole-net
```
