### ISSUE TITLE
/admin (login page) keeps refreshing constantly

### ISSUE THREAD

**Issue by rutvora** [pi-hole/pi-hole#6212]
### Versions

- Pi-hole:  v6.0.6
- Web:  v6.1
- FTL:  v6.1

### Platform

- OS and version:  Ubuntu 24.04.2

- Platform:  Docker (Issue persists on both x86 and arm64)

### Expected behavior

/admin should not refresh constantly.

### Actual behavior / bug

/admin keeps refreshing constantly (imagine that someone is quickly and repeatedly pressing the refresh button).
Manually stopping the refresh works, and I can type in the password to login.
However, after logging in, I don't see any stats or configuration (I have stats enabled). 
I can't see any block lists when I click on "Lists" in the left-side panel (even though I do have a list and can see it and query it on the CLI).
Similarly, I can't even see settings (it just keeps showing the loading spinner).
Browser debugger doesn't even show any request as pending in any of these cases.

Basically, I am unable to access and configure the pihole from the GUI after logging in.

### Steps to reproduce

Just visit <PIHOLE>/admin

## Debug Token

- URL:  https://tricorder.pi-hole.net/UPu8A7Ue/

### Additional context

My docker-compose config:

```
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "80:80/tcp"
#      - "443:443/tcp"
    environment:
      TZ: "Asia/Kolkata"
      FTLCONF_webserver_api_password: 'correct horse battery staple'
     
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      # - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # - './resolv.conf:/etc/resolv.conf'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.19.0.220

networks:
  default:
      name: http-traffic
      external: true
```

I access pihole behind an Nginx proxy (for web/GUI) and a wireguard tunnel (for DNS).
The wireguard tunnel for DNS works fine.
Nginx config below:

```
server {
    listen 443 ssl;
    http2 on;
    server_name pihole.<SITE>;

    gzip on;
    gzip_types application/javascript image/* text/css;
    gunzip on;

    ssl_certificate /etc/letsencrypt/live/<SITE>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<SITE>/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_pass http://pihole; 
    }
}

```

Nginx can load all other sites hosted correctly, with similar config params
