### ISSUE TITLE
PiHole admin interface does not work properly when running in a subfolder e.g. https://myserver/pihole/admin

### ISSUE THREAD

**Issue by extorn** [pi-hole/pi-hole#6225]
### Versions
- Pi-hole:  v6.0.6
- Web:  v6.1
- FTL:  v6.1

### Platform
- OS and version:  

- Platform:  Docker

### Expected behavior

UI Should work exactly as when accessed from root - i.e. the following two pages should look identical (when the system is fired up with adjusted root).
https://myserver/admin/groups/lists
https://myserver/pihole/admin/groups/lists

### Actual behavior / bug

Three are listed, I'm certain all are linked to the same cause.

1. The select picker form controls are constantly showing, rather than appearing on click
2. When toggling enabled status of a subscribed list, it creates a copy of the subscribed list entry in the web ui with the new status rather than updating the one you toggle.

### Steps to reproduce

0. Create PiHole docker container using image "FROM pihole/pihole:latest"
1. Create a basic Docker compose file (the most basic will suffice)
2. Start PiHole. Login and access page: https://myserver/admin/groups/lists
3. Note the webpage behaves correctly
4. Stop PiHole.
5. In your docker compose, add the following override in the "environment:" section
         FTLCONF_webserver_paths_prefix: '/pihole'
6.Start PiHole.  Login and access page: https://myserver/pihole/admin/groups/lists
7. Note the webpage behaves incorrectly - 
8. Open webdeveloper tools.
9. Note that a css file failed to load correctly as it is trying to load from https://myserver/admin/
     (https://myserver/admin/vendor/icheck/icheck-bootstrap.min.css)
10. Correct load error by editing file /var/www/html/admin/scripts/js/footer.js, line 200. change as follows:
         ```return apiUrl+"/../vendor/icheck/icheck-" + extra + ".min.css";```
	Here is a sed command to do so: 
```sed 's|"/admin/vendor/icheck/icheck-|apiUrl+"/../admin/vendor/icheck/icheck-|g' -i /var/www/html/admin/scripts/js/footer.js```
11. Correct another error with hardcoded URI in same file (line 732):
		```sed 's|"/admin/settings/system|apiUrl+"/../admin/settings/system|g' -i /var/www/html/admin/scripts/js/footer.js```
12. Correct another error with hardcoded URI in different file (my fix is untested):
		```sed 's|/admin/gravity|<?=webhome?>admin/gravity|g' -i /var/www/html/admin/settings-teleporter.lp```
11. access page: https://myserver/pihole/admin/groups/lists
12. Note that css load error goes away, but unfortunately, the corruption noted in the bugs seen does not alter (page still corrupted).

## Debug Token

I was unable to get to the bottom of finding a debug token (started docker container using environment variable FTL_CMD=debug, but didn't seem to help - maybe I missed it)

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

![Image](https://github.com/user-attachments/assets/5950f35a-d44d-4dc4-9d13-55c82335b2b2)
![Image](https://github.com/user-attachments/assets/2d67deed-4086-4480-9309-57babdad562d)

_Add any other context about the problem here._

I start a series of linked services up in docker, but here is the configuration for the docker service in my compose file, my data obfuscated
```
  pihole:
    container_name: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
	restart: unless-stopped
	cap_add:
# allow setting time.
       - SYS_TIME
# setting process priority
       - SYS_NICE
# handling ipv6 requests
       - NET_RAW
    environment:
      PIHOLE_UID: '1009'
      PIHOLE_GID: '1009'
      TZ: 'Europe/London'
# Enable DNSSEC mode
#      DNSSEC: 'true'
# conditional forwarding for device name resolution
      REV_SERVER: 'true'
      REV_SERVER_TARGET: '192.168.0.1'
      REV_SERVER_CIDR: '192.168.0.0/24'
# local dhcp domain (note to self: is this needed?)
      REV_SERVER_DOMAIN: 'upstream.dhcp.server'
#      FTLCONF_LOCAL_IPV4: '192.168.0.6'
      WEBPASSWORD: '5l1Fu8iVHRhAKFt5Gcb9'
#      - SERVERIP=192.168.0.6
#      FTL_CMD: 'debug'
      DNSMASQ_LISTENING: 'all'
      FTLCONF_webserver_paths_prefix: '/pihole'
      FTLCONF_webserver_domain: 'myservername.mydomain'
# this enables ssl support all the way to this server if wanted...
      FTLCONF_webserver_tls_cert: '/etc/pihole/myservername.crtkey.pem'
```
